let num = 10;
let str = 'John';
let bool = true;
let what = undefined;
alert(typeof(num));
alert(typeof(str));
alert(typeof(bool));
alert(typeof(what));
let num2 = 69;
let num3 = 1234;
alert(num2+num3);
let str2 = 'John2';
alert(str+str2);
alert( str > str2 );
alert( str[2] );